version: 2.1

# https://github.com/CircleCI-Public/circleci-demo-aws-eks/blob/master/.circleci/config.yml

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  aws-eks: circleci/aws-eks@0.2.0
  kubernetes: circleci/kubernetes@0.3.0  

jobs:
  create-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      resource-name:
        description: |
          Name of the deployment resource
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          resource-file-path: "k8s.yml"
          resource-name: << parameters.resource-name >>
          get-rollout-status: true
          show-kubectl-command: true


workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: backend/backend.dockerfile
          path: .
          region: AWS_REGION
          repo: trainx-dev
          tag: "$CIRCLE_SHA1"

      - create-deployment:
          cluster-name: ks-dev
          resource-name: backend-deployment
          requires:
            - aws-ecr/build-and-push-image