apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: DOCKER_IMAGE_NAME
        # imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: environ
        env:
        - name:  SERVER_NAME
          value: 'localhost'
        - name:  SERVER_HOST
          value: 'http://localhost'
        - name: VERSION_INFO
          value: "VERSION_INFO_VALUE"
        - name: BUILD_DATE
          value: "BUILD_DATE_VALUE"
        ports:
        - containerPort: 80

# kubectl create secret generic backend-secret --from-file='.env'
# kubectl create configmap environ --from-env-file=.env
# kubectl create configmap --dry-run environ --from-file=.env --output yaml | tee somename.yaml
# kubectl exec --stdin --tty backend-deployment-c4759d466-ns2x9 -- /bin/bash