apiVersion: v1
kind: ConfigMap
metadata:
  name: environ

data:
  # Backend
  PROJECT_NAME: trainx-backend
  FIRST_SUPERUSER: admin@trainx-backend.com
  FIRST_SUPERUSER_PASSWORD: changethis
  USERS_OPEN_REGISTRATION: 'True'
  SENTRY_DSN: ''

  # Postgres
  POSTGRES_SERVER: 'dev-database.ctstu40cqil2.us-east-2.rds.amazonaws.com'
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: changethis
  POSTGRES_DB: postgres

  # Strava
  STRAVA_CLIENT_ID: '49328'
  STRAVA_CLIENT_SECRET: b20d6d5ee200036f6ca331d3bd12cd2a9d31fb6b
  STRAVA_WEBHOOK_VERIFY_TOKEN: 'f7be6480-05bc-45c1-9e00-d24a926ea1e5'

