"""Add column refresh_token

Revision ID: 25bfd2f212e8
Revises: ac323b5895ff
Create Date: 2020-06-09 18:29:56.457238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25bfd2f212e8'
down_revision = 'ac323b5895ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_user', sa.Column('external_user_refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_user', 'external_user_refresh_token')
    # ### end Alembic commands ###
