"""Add user_facebook table

Revision ID: 3fe28cbf0589
Revises: 9b6b971007f2
Create Date: 2020-06-09 06:56:36.719145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe28cbf0589'
down_revision = '9b6b971007f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userfacebook',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('full_name', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('facebook_user_id', sa.String(), nullable=False),
                    sa.Column('owner_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_userfacebook_email'), 'userfacebook', ['email'], unique=True)
    op.create_index(op.f('ix_userfacebook_facebook_user_id'), 'userfacebook', ['facebook_user_id'], unique=True)
    op.create_index(op.f('ix_userfacebook_full_name'), 'userfacebook', ['full_name'], unique=False)
    op.create_index(op.f('ix_userfacebook_id'), 'userfacebook', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userfacebook_id'), table_name='userfacebook')
    op.drop_index(op.f('ix_userfacebook_full_name'), table_name='userfacebook')
    op.drop_index(op.f('ix_userfacebook_facebook_user_id'), table_name='userfacebook')
    op.drop_index(op.f('ix_userfacebook_email'), table_name='userfacebook')
    op.drop_table('userfacebook')
    # ### end Alembic commands ###
