"""Add external_user table

Revision ID: ac323b5895ff
Revises: 3fe28cbf0589
Create Date: 2020-06-09 18:10:39.718542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac323b5895ff'
down_revision = '3fe28cbf0589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_user_id', sa.String(), nullable=False),
    sa.Column('external_source', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('external_user_access_token', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_user_external_source'), 'external_user', ['external_source'], unique=True)
    op.create_index(op.f('ix_external_user_external_user_id'), 'external_user', ['external_user_id'], unique=True)
    op.create_index(op.f('ix_external_user_id'), 'external_user', ['id'], unique=False)
    op.drop_index('ix_userfacebook_email', table_name='userfacebook')
    op.drop_index('ix_userfacebook_facebook_user_id', table_name='userfacebook')
    op.drop_index('ix_userfacebook_full_name', table_name='userfacebook')
    op.drop_index('ix_userfacebook_id', table_name='userfacebook')
    op.drop_table('userfacebook')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userfacebook',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('facebook_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='userfacebook_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='userfacebook_pkey')
    )
    op.create_index('ix_userfacebook_id', 'userfacebook', ['id'], unique=False)
    op.create_index('ix_userfacebook_full_name', 'userfacebook', ['full_name'], unique=False)
    op.create_index('ix_userfacebook_facebook_user_id', 'userfacebook', ['facebook_user_id'], unique=True)
    op.create_index('ix_userfacebook_email', 'userfacebook', ['email'], unique=True)
    op.drop_index(op.f('ix_external_user_id'), table_name='external_user')
    op.drop_index(op.f('ix_external_user_external_user_id'), table_name='external_user')
    op.drop_index(op.f('ix_external_user_external_source'), table_name='external_user')
    op.drop_table('external_user')
    # ### end Alembic commands ###
