"""Add column expires at

Revision ID: ea343438fce9
Revises: 25bfd2f212e8
Create Date: 2020-06-14 16:37:54.858422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea343438fce9'
down_revision = '25bfd2f212e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_user', sa.Column('external_user_access_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_user', 'external_user_access_token_expires_at')
    # ### end Alembic commands ###
